#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

if os.listdir('/run/log/journal'):
    agent.set_env("PROMTAIL_JOURNAL", "/run/log/journal")
else:
    agent.set_env("PROMTAIL_JOURNAL", "/var/log/journal")

