#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import json
import sys
import os

node_id = os.environ["NODE_ID"]
module_id = os.environ["MODULE_ID"]

event_source = os.environ["AGENT_EVENT_SOURCE"]

event_data = json.load(sys.stdin)

if event_source != 'cluster':
    sys.exit(0)

if str(event_data["node"]) != node_id:
    sys.exit(0) # Ignore if module was added to another node

agent.run_helper('systemctl', 'try-restart', '-T', f"{module_id}.service")
